// GitHub-style language color palette and file-extension → language mapping.

export const LANGUAGE_COLORS: Record<string, string> = {
  TypeScript:   "#3178c6",
  JavaScript:   "#f1e05a",
  Python:       "#3572A5",
  "C#":         "#178600",
  Java:         "#b07219",
  "C++":        "#f34b7d",
  C:            "#555555",
  Go:           "#00ADD8",
  Rust:         "#dea584",
  Swift:        "#F05138",
  Kotlin:       "#A97BFF",
  Ruby:         "#701516",
  PHP:          "#4F5D95",
  HTML:         "#e34c26",
  CSS:          "#563d7c",
  SCSS:         "#c6538c",
  Less:         "#1d365d",
  Shell:        "#89e051",
  PowerShell:   "#012456",
  YAML:         "#cb171e",
  JSON:         "#292929",
  XML:          "#0060ac",
  Markdown:     "#083fa1",
  SQL:          "#e38c00",
  Dockerfile:   "#384d54",
  HCL:          "#844FBA",
  Vue:          "#41b883",
  Svelte:       "#ff3e00",
  R:            "#198CE7",
  Scala:        "#c22d40",
  Groovy:       "#4298b8",
  Dart:         "#00B4AB",
  Lua:          "#000080",
  Perl:         "#0298c3",
  Haskell:      "#5e5086",
  Elm:          "#60B5CC",
  MATLAB:       "#e16737",
  Other:        "#8f8f8f",
};

export const EXTENSION_TO_LANGUAGE: Record<string, string> = {
  ".ts":    "TypeScript",
  ".tsx":   "TypeScript",
  ".mts":   "TypeScript",
  ".cts":   "TypeScript",
  ".js":    "JavaScript",
  ".jsx":   "JavaScript",
  ".mjs":   "JavaScript",
  ".cjs":   "JavaScript",
  ".py":    "Python",
  ".pyw":   "Python",
  ".cs":    "C#",
  ".csx":   "C#",
  ".java":  "Java",
  ".cpp":   "C++",
  ".cc":    "C++",
  ".cxx":   "C++",
  ".hpp":   "C++",
  ".hxx":   "C++",
  ".c":     "C",
  ".h":     "C",
  ".go":    "Go",
  ".rs":    "Rust",
  ".swift": "Swift",
  ".kt":    "Kotlin",
  ".kts":   "Kotlin",
  ".rb":    "Ruby",
  ".erb":   "Ruby",
  ".php":   "PHP",
  ".html":  "HTML",
  ".htm":   "HTML",
  ".css":   "CSS",
  ".scss":  "SCSS",
  ".sass":  "SCSS",
  ".less":  "Less",
  ".sh":    "Shell",
  ".bash":  "Shell",
  ".zsh":   "Shell",
  ".fish":  "Shell",
  ".ps1":   "PowerShell",
  ".psm1":  "PowerShell",
  ".psd1":  "PowerShell",
  ".yml":   "YAML",
  ".yaml":  "YAML",
  ".json":  "JSON",
  ".xml":   "XML",
  ".xsl":   "XML",
  ".xslt":  "XML",
  ".md":    "Markdown",
  ".mdx":   "Markdown",
  ".sql":   "SQL",
  ".tf":    "HCL",
  ".tfvars":"HCL",
  ".hcl":   "HCL",
  ".vue":   "Vue",
  ".svelte":"Svelte",
  ".r":     "R",
  ".R":     "R",
  ".scala": "Scala",
  ".sc":    "Scala",
  ".groovy":"Groovy",
  ".gvy":   "Groovy",
  ".dart":  "Dart",
  ".lua":   "Lua",
  ".pl":    "Perl",
  ".pm":    "Perl",
  ".hs":    "Haskell",
  ".elm":   "Elm",
  ".m":     "MATLAB",
  Dockerfile: "Dockerfile",
};

export const BINARY_EXTENSIONS = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".ico", ".svg", ".webp", ".bmp", ".tiff",
  ".woff", ".woff2", ".ttf", ".eot", ".otf",
  ".zip", ".tar", ".gz", ".bz2", ".7z", ".rar",
  ".jar", ".war", ".ear", ".class",
  ".dll", ".exe", ".so", ".dylib", ".a", ".lib",
  ".bin", ".dat", ".db", ".sqlite",
  ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
  ".mp3", ".mp4", ".avi", ".mov", ".wav",
  ".lock",
  ".map",
]);

/** Returns the lowercase file extension (e.g. ".ts") or "Dockerfile" for known extensionless files. */
export function getFileExtension(filePath: string): string {
  const fileName = filePath.split("/").pop() ?? filePath;
  if (fileName === "Dockerfile" || /^Dockerfile\.\w+$/.test(fileName)) return "Dockerfile";
  const dot = fileName.lastIndexOf(".");
  if (dot <= 0) return "";
  return fileName.slice(dot).toLowerCase();
}
